"""Export repository Python files into one Markdown document."""

from __future__ import annotations

import argparse
from pathlib import Path

EXCLUDED_DIRS = {".git", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tinyagent", ".venv", "__pycache__"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output",
        nargs="?",
        default="docs/PY_SOURCE_EXPORT.md",
        help="Markdown file to write. Defaults to docs/PY_SOURCE_EXPORT.md.",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    output = (repo_root / args.output).resolve()
    files = list(iter_python_files(repo_root))

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(repo_root, files))

    print(f"wrote {output.relative_to(repo_root)} with {len(files)} Python files")
    return 0


def iter_python_files(root: Path) -> list[Path]:
    return sorted(path for path in root.rglob("*.py") if not any(part in EXCLUDED_DIRS for part in path.parts))


def render(repo_root: Path, files: list[Path]) -> str:
    lines = [
        "# Python Source Export",
        "",
        "Generated by `scripts/export_py_markdown.py`.",
        "",
    ]
    for path in files:
        relative = path.relative_to(repo_root).as_posix()
        lines.extend(
            [
                f"## `{relative}`",
                "",
                "```python",
                path.read_text().rstrip(),
                "```",
                "",
            ]
        )
    return "\n".join(lines)


if __name__ == "__main__":
    raise SystemExit(main())
